### ISSUE TITLE
Improve GC

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/llvm-backend#45]
- [x] collect old generation
- [x] collect ints and floats
- [x] give struct stringbuffer a proper header
- [x] use block-entry alloca for sret
- [x] collect collections
- [ ] remove unnecessary load in struct layout

**Comment by bmmoore** [comment]
Rather than simply removing the load in struct layout, we should probably try to arrange things so most layouts can be decoded from the header word alone, without needing any hash lookup at all.

**Comment by Baltoli** [comment]
@theo25 What's the status of this?

**Comment by ehildenb** [comment]
Closing for now, can re-open if we revisit.

**Comment by ehildenb** [comment]
@theo25 please link to the upstream patches you've submitted here, and follow up on them. Then we can close.

**Comment by theo25** [comment]
Here is the link to the upstream patch with a fix required for unwindig the stack of interpreters generated by the LLVM backend using libunwind: [https://reviews.llvm.org/D143618](https://reviews.llvm.org/D143618)

**Comment by Baltoli** [comment]
@theo25 has been asked for a test by the LLVM team.

**Comment by dwightguth** [comment]
We should be able to use the minimized test case I wrote when I was evaluating the issue. It will just need to be given appropriate lit directives.

**Comment by theo25** [comment]
@dwightguth Unfortunately that test case does not trigger the bug, because its functions do not require any additional stack space when tail called. But I think I can modify it and get the required behavior for the bug to  trigger

**Comment by Baltoli** [comment]
https://github.com/llvm/llvm-project/commit/2e0940c6a0857e3cc6aecfe7dd0c4cde94e1ae9a patch has now landed - @theo25 can the issue be closed now?
