### ISSUE TITLE
support full generality of heating and cooling nondeterminism

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/llvm-backend#473]
Right now the LLVM and Haskell backends require that a term that is heated be fully evaluated before being cooled. If the frontend were to remove the side condition on the cooling rule, this would lead to infinite loops where the heating and cooling rules apply in cycles. However, the current behavior loses some behaviors that are actually allowed by the full generality of heating and cooling, namely, the ones where something is heated, partially evaluated, then cooled and heated again later. Essentially, we want to somehow modify either the frontend or the backend so that we can get all behaviors without the problem of looping forever.

**Comment by Baltoli** [comment]
@dwightguth going to close this as it's subsumed by your newer issue here: https://github.com/runtimeverification/k/issues/3185
