### ISSUE TITLE
Binary serialization of parametric productions

### ISSUE THREAD

**Issue by gtrepta** [runtimeverification/llvm-backend#535]
#529 and #533 Are fixing specific cases of serializing a parametric production. We need to handle the general case since there can be more of them.

**Comment by ehildenb** [comment]
We have parsers for kore that handle this generality, it sounds like the LLVM backend binary serializer, because it uses a different representation for the parameters of parametric labels. This works, because there are only 2 cases that the LLVM backend uses at the moment.

**Comment by Baltoli** [comment]
Fixed by https://github.com/runtimeverification/llvm-backend/pull/540
