### ISSUE TITLE
`#trace` broken on Apple M1

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/llvm-backend#536]
The trace regression test in K repo: https://github.com/runtimeverification/k/blob/master/k-distribution/tests/regression-new/trace/test.k

is failing with 

```bash
make[1]: Entering directory '/private/tmp/nix-build-k-5.3.0-dirty-test.drv-0/source/tests/regression-new/trace'
/nix/store/gmphfy9df8zfhxfn9y29cwcjnf3j63ym-k-5.3.0-dirty/bin/kompile --syntax-module TEST --no-exc-wrap --no-haskell-binary --backend llvm  test.k -d .
make[1]: Entering directory '/private/tmp/nix-build-k-5.3.0-dirty-test.drv-0/source/tests/regression-new/trace'
set -o pipefail; (cat 1.test.in 2>/dev/null || true) | /nix/store/gmphfy9df8zfhxfn9y29cwcjnf3j63ym-k-5.3.0-dirty/bin/krun 1.test --no-exc-wrap  -d . 2>&1 | diff - 1.test.out
1,2c1,8
< Syntax error at traceKORE_LkG4Ju:1.16: Expected: <identifier> Actual: (
< [Error] krun: Backend crashed during rewriting with exit code 255
---
> foo ( 34 )
> frob ( "Hello" , false )
> "builtin"
> bar
>   foo ( 2 ) * foo ( 0 )
> <k>
>   .
> </k>
```

when ran against K with llvm-backend at commit [8243ca9e201f9be793b57ddfb54cc77043a14dd4](https://github.com/runtimeverification/llvm-backend/commit/8243ca9e201f9be793b57ddfb54cc77043a14dd4) on M1 MacBook Pro

attached below is the kompiled output from of the `trace/` folder:
[trace.zip](https://github.com/runtimeverification/llvm-backend/files/9009324/trace.zip)

**Comment by Baltoli** [comment]
@goodlyrottenapple This has been resolved as of LLVM backend commit https://github.com/runtimeverification/llvm-backend/commit/0cd4cd1831428b1fe23b6adbb28cd99e13adcae9
