### ISSUE TITLE
Using `--debugger` mode on krun is incompatible with `-O0`

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/llvm-backend#542]
A client is developing a semantics using K using the LLVM backend.

Unfortunately, building the particualr semantics using `-ccopt -O1` (needed to use the LLVM backend GDB extension) causes the `llc` to get stuck on the register allocation phase; I once let it run for over an hour without finishing.

It would be helpful if we can still run the debugger mode on semantics compiled with `-ccopt -O0` since this seems to use a much simpler register allocation algorithm.

**Comment by sskeirik** [comment]
I understand that @theo25 might be able to take a look at this when he comes back from break.

**Comment by dwightguth** [comment]
Over an hour is significantly more than I've seen it take before. How much RAM was on the machine you tried it with?

**Comment by dwightguth** [comment]
also, what is the file size of the file it's stuck trying to `llc`?

**Comment by sskeirik** [comment]
I'm not sure about filesize so I'll get back to you on that soon --- the headless VM running the build is assigned 32 GBs of RAM and uses about 300 MBs of RAM at idle.

**Comment by Baltoli** [comment]
I'm back from my holiday and can take a look at this @sskeirik - do you have a reproducible example handy that I can run?

**Comment by sskeirik** [comment]
@Baltoli The build/test process is currently a bit painful. I have a couple of PRs in flight that will hopefully smooth out this all out. Once they are merged, I will work on writing up some instructions.

**Comment by Baltoli** [comment]
@sskeirik Is this still an issue / did you produce the reproduction steps?

**Comment by Baltoli** [comment]
I plan to start working more earnestly on LLDB integration for K; if you'd like us to look specifically at this again please reopen it @sskeirik 

https://github.com/runtimeverification/k/issues/2650
