### ISSUE TITLE
[KIP] - add a version of `#parseKORE` that can handle ill-formed input

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/llvm-backend#580]
Motivation
----------

Currently, when `#parseKORE` is called on a string which is not valid Kore in a semantics compiled using the LLVM backend, the semantics interpreter crashes. This means that we cannot have:

-   custom error messages for Kore parse errors - we get whatever the hook gives us
-   custom error handling for Kore parse errors - we crash

Allowing for a custom error handling routine for our tools which parse Kore will make our tooling appear more polished to our clients and make debugging slightly easier.

As an example, we have a tool for a client where we use `#unparseKORE` to store values in a database and `#parseKORE` to read them out. Currently, if for any reason, for example, due to WIP code, upgrades, network issues, random bit-flips, etc. the semantics and the database get out of sync then the client will just see something like this:

```
...
/home/stephen/work/kframework/master/k-distribution/target/release/k/bin/krun: line 70:  2462 Aborted                 "$@"
[Error] Critical: Backend crashed during rewriting with exit code 134
```

where the `...` seems to be the first token encountered which the parser failed to parse. To a non-technical user, this will be confusing at best and give us a bad look at worst.

Example K Code
--------------

Ideally, we would like a version of `#parseKORE` which is a provably total function at compile time. For this new version to work, we have a couple different possible approaches as far as I can see:

1.  provide a default value which matches the inferred target sort

```
syntax {Sort} Sort ::= #parseKORE(String, Sort) [hook(...)]

// Behavior:
//
// Given:
//
// syntax Int ::= #parseInt(String) [function, functional]
// rule #parseInt(S) => #parseKORE(S, -1)
// 
// We expect:
//
// #parseInt("... valid Kore for Int 5 ...") => 5
// #parseInt("foo") => -1
```

2.  provide a default value and an explicit target sort (may help with debugging):

```
// NB:
// 1.  the first String argument below represents a K Sort
// 2.  the second String argument below represents the Kore to be parsed
//
syntax {Sort} Sort ::= #parseKORE(String, String, Sort) [hook(...)]

// Behavior:
//
// #parseKORE("Int", "... valid Kore for Int 5 ..", -1) =>  5
// #parseKORE("Int", "foo", -1)                         => -1
// #parseKORE("----", "foo", -1)                              // compile error 
```

3.  return a fresh sort for parse results

```
syntax KParseResult ::= KParseResult(K)
                      | KParseFailure(String)
                    
// NB:
// 1. the first String argument below represents a K Sort
// 2. the second String argument below represents the Kore to be parsed
//
syntax KParseResult ::= #parseKORE(String, String) [function, hook(...)]

// Behavior:
//
// #parseKORE("Int", "... valid Kore for Int 5 ...") => KParseResult(5)
// #parseKORE("Int", "foo") => KParseFailure("an error message")
```

Documentation
-------------

The `#parseKORE` family of functions all operate as follows:

1.  they infer their output sort `T` based on where they occur in the K AST (or perhaps are given an explicit target sort `T`)
2.  they take a `String` as input and attempt parse it as Kore representation of some arbitrary `T` value `v`
3.  if the parse is successful, the value `v` is returned (or a `KParseResult` is returned)

Where the members of this family differ is in how they handle Kore parse errors:

1.  when the function `#parseKORE(String)` is called with a `String` that is invalid Kore, it raises a runtime error and interpretation halts
2.  when the function `#parseKORE(..., String, ...)` is called with a `String` that is invalid Kore, it returns a default `T` value (or a `KParseFailure` is returned)

Potential Alternatives/Work-arounds
-----------------------------------

This functionality is not required for any semantics that we write --- it is just a quick, easy, and fast way to load data into a K semantics.

We could always write explicit unparsers and parsers in K code do all parsing/unparsing internally and have full control over the error messages and error handling. The downside to this approach is that it is much more work intensive.

Testing Approach
----------------

Testing this feature would require a small test files using examples similar to the ones I used above and would have no problems being integrated into the standard K test harness.

**Comment by Baltoli** [comment]
I'm going to close this issue:
* As Dwight identifies, the implementation in the LLVM backend is non-trivial
* Since the issue was opened, the way that we write semantics has substantially evolved, and directly loading an unvalidated KORE term into the backend is unlikely to be the idiomatic way to implement the underlying task that motivated this issue.

If it remains an issue, we can reopen it in the future.
