### ISSUE TITLE
`sprintf` is deprecated on macOS Ventura

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/llvm-backend#589]
macOS Ventura, released on October 24, 2022, has deprecated `sprintf`, leading to LLVM backend build failures on this OS version.

Running the following grep command, I found:

```
> rg sprintf --count | rg -v '.md:'
runtime/strings/strings.cpp:1
deps/rapidjson/test/unittest/jsoncheckertest.cpp:3
deps/rapidjson/test/unittest/encodedstreamtest.cpp:1
deps/immer/tools/include/doctest.h:11
deps/rapidjson/test/perftest/perftest.h:1
deps/rapidjson/test/perftest/misctest.cpp:4
deps/rapidjson/test/perftest/schematest.cpp:2
deps/rapidjson/test/unittest/documenttest.cpp:1
deps/rapidjson/test/unittest/schematest.cpp:2
deps/rapidjson/test/unittest/istreamwrappertest.cpp:1
deps/rapidjson/test/unittest/valuetest.cpp:7
deps/rapidjson/test/unittest/readertest.cpp:1
deps/rapidjson/example/jsonx/jsonx.cpp:5
deps/rapidjson/example/tutorial/tutorial.cpp:1
```

It looks like the one instance in `strings.cpp` will need to be replaced with `snprintf`.

All of the other hits look like test files for our dependencies. We should look to see if these libraries have been updated, so that tests can run on all macOS versions.

**Comment by Baltoli** [comment]
@sskeirik I'm just updating my machine to Ventura now to investigate this.

Do the uses in `rapidjson` and `immer` actually end up getting compiled (and therefore throwing the deprecation error?), or is it just the single use in our code?

**Comment by sskeirik** [comment]
I suppose that the tests are only built on demand, if at all, but I actually don't know.

One could check out the mvn options to see if any of this test code ever gets built.
