### ISSUE TITLE
Investigate memory usage from simplification

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#635]
@goodlyrottenapple and @jberthold report memory leaks when using the RPC server to make many requests to the backend in _one process_. We should look into this. Possible fixes:
* Identify the memory leak and fix it; @goodlyrottenapple has supplied an example trace from the backend that can be used from C.
* Cache terms haskell-side; this needs a change to the memory model of the AST structures

**Comment by dwightguth** [comment]
I mean, if terms aren't being shared between requests, you probably just need to call a function to free all memory after each request.

**Comment by dwightguth** [comment]
I believe the function you want is called freeAllKoreMem.

**Comment by jberthold** [comment]
If that function is accessible from the library it would definitely solve the problem.
Caching on the Haskell side would not, the cache would grow just like the LLVM memory footprint does, and we would still be unable to free memory when we GC that cache.

**Comment by jberthold** [comment]
Just discussed this with @goodlyrottenapple : we should indeed do both,  cache the terms _within one request_, and clear the entire kore memory after a request is complete

**Comment by goodlyrottenapple** [comment]
As far as I understand, the `freeAllKoreMem` function does not actually free any of the memory for `KoreCompoistePattern`s etc.? If that is the case, we need to get `freeAllKoreMem` working reliably before being able to tell how much memory is leaking from the marshalling vs currently uncollected GC memory.

**Comment by dwightguth** [comment]
You are correct. freeAllKoreMem essentially just runs the llvm backend's garbage collector, with the effect that it will free all memory allocated on the garbage collected heap which is no longer reachable. If nothing is reachable, it will free everything in constant time. If you are concerned about memory management of classes in the kllvm::ast hierarchy, those are allocated via c++ smart pointers. You will need to somehow keep track of ownership of these objects and run their destructors when they are no longer reachable. If you are maintaining those pointers as haskell terms, you probably will want to make use of a finalizer.

**Comment by Baltoli** [comment]
The C objects exposed by the API all have `kllvm_$TYPE_free` functions available; if you call them when you no longer need the object, the AST part shouldn't leak memory.

I found that you can leak a surprising amount of memory if you don't do this; I would recommend making sure that finalizers etc. are set up to clean the AST nodes you don't need before you spend too much time on the backend GC.

**Comment by ehildenb** [comment]
Some data: https://runtimeverification.slack.com/archives/CC360GUTG/p1675330182303479

**Comment by Baltoli** [comment]
I'm going to close this for now as it's not actively being worked on; if we come back to it and find that there's a specific memory issue to be investigated with the bindings then we can open a new issue for that.
