### ISSUE TITLE
Make serializer API thread-safe

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#643]
The binary serializer (and textual printer) use `static thread_local` storage to maintain state within a call. This causes issues when multiple calls are made to the serializer at the same time from *non-OS threads* (e.g. within the Haskell runtime).

We should thread the static state through each call so that the new haskell backend can do multiple simplifications at a time.

Making this change will require a change to the visitor code-generation; I suspect that the best way to do this without a great deal of added complexity is to add an extra pointer argument that the C++ code can treat as a state structure.

**Comment by Baltoli** [comment]
@jberthold is double-checking that #644 still has an issue; if so we should come up with some C-side tests that demonstrate the issue.

https://github.com/sustrik/libdill as a way to demonstrate?

**Comment by Baltoli** [comment]
Blocked on a minimal example I can use locally to demonstrate a failure.

**Comment by Baltoli** [comment]
Not sure if this is currently affecting anything.

**Comment by jberthold** [comment]
We might want to parallelise rewriting and/or simplification at some point in the future if we can fix this issue. However, this is only an idea for now and would not justify  expensive changes.

**Comment by Baltoli** [comment]
The booster now uses its own strategy to parallelise uses of the bindings.
