### ISSUE TITLE
Support for `[functional]` to `[total]` migration

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#667]
Multi-stage deprecation

**Comment by ehildenb** [comment]
Might be the case that the llvm backend largely ignores functional/total anyway.

**Comment by ehildenb** [comment]
One complication: the LLVM backend CI integration tests use raw kore files committed directly to repo.

- Could change the kore files directly (maybe will invalidate digests in those files though?)
- Could regenerate the kore files if needed (hard).
