### ISSUE TITLE
`k-rule-find` only returns one rule and miss support for rules generated with `strict` and `seqstrict`

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/llvm-backend#725]
Currently, the `heating` and `cooling` rules generated by `strict` and `seqstrict` attributes don't have a rule **label**, so the tool can't find it.  Also, the tool only returns a single rule where it can have multiple rules. 

For the first issue, https://github.com/runtimeverification/k/pull/3063 may be helpful in fixing it.
For the second issue, we must get a way to return it in multiple lines on the output.

**Comment by radumereuta** [comment]
We need to handle the case of multiple rules on a single line.
Also, a production can generate multiple rules with the same location.
