### ISSUE TITLE
Support LLVM 16

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#730]
LLVM 16 was released a few weeks ago and is already the default version for Homebrew. We should test the LLVM backend to make sure that it can be built with version 16; if not we need to update documentation pointing to Homebrew formulae to reflect this.

Running with version 16 in CI is blocked until the Nix maintainers ship it properly; work appears to already be ongoing here. We should nevertheless still check macOS informally.

* Homebrew formula page: https://formulae.brew.sh/formula/llvm#default
* Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/223282

Things that need to be changed:
* [x] Uses of `getInstList` on a basic block
* [x] `getABITypeAlign[ment]`
* [x] Invocation of `opt`

**Comment by RaitoBezarius** [comment]
FWIW, LLVM16 will (hopefully) be part of NixOS 23.05 and land in unstable soon.

**Comment by Baltoli** [comment]
Thanks @RaitoBezarius - that's helpful to know!

**Comment by Baltoli** [comment]
@theo25 to investigate the use of opaque pointers in this version

**Comment by theo25** [comment]
I looked into the release notes of LLVM 16 and it does not seem that the use of opaque pointers is mandated by this release. However, the release notes found in the main branch on github do list [the opaque pointer change](https://github.com/llvm/llvm-project/blob/main/llvm/docs/ReleaseNotes.rst#changes-to-the-llvm-ir), so we can assume that the change is coming with the LLVM 17 release.

**Comment by Baltoli** [comment]
The Opaque Pointers migration document reveals that their introduction is not _mandatory_ in LLVM 16, but they are enabled by default and the old system is no longer supported. This suggests that the LLVM 16 transition is the right point at which to make sure they work properly for the LLVM backend.

Some debugging reveals that there is a subtle issue we have previously missed when migrating over to opaque pointers. In transparent mode, we make equality comparisons between pointer types: https://github.com/runtimeverification/llvm-backend/blob/046b5968778c4cb1fa8bc5b69918248e41504bb4/lib/codegen/EmitConfigParser.cpp#L852-L854

These comparisons have their semantics changed silently when moving to opaque pointers. Previously, we'd have seen a comparison of `A* == B*` (with meaningful semantics depending on the pointee types `A`, `B`). However, now both sides of the comparison are now `ptr` and the comparison is silently failing. We need to audit the codebase for places where we're comparing pointer types in this way and fix them (similarly to previous changes) to compare the _underlying_ types in a meaningful way.

**Comment by Baltoli** [comment]
This is possibly a tricky change, and so we should also update the documentation for macOS to reflect the fact that we don't yet support LLVM 16. Otherwise, we'll get breakages there for people building from source.

**Comment by dwightguth** [comment]
Ahhh. This is a good catch. This relates to how we are passing map, list, and set terms around at the llvm bytecode level. I don't remember the exact details. I can dig into it and try and refresh my memory if you'd like.

**Comment by dwightguth** [comment]
I believe that it was meant to only evaluate to true in the case involving map and map*, list and list*, and set and set* though, which is a comparison that could still be made with opaque pointers. The fix might be as simple as just wrapping each of these clauses in a guard against the sort category in question.

**Comment by Baltoli** [comment]
I did a quick dig into the code and that's the same conclusion I came to before seeing your comment. A grep suggests there are only a few places that we do it, so I will try making the change to check the sort category explicitly rather than relying on the pointer types and see how far that gets me. Thanks!

**Comment by Baltoli** [comment]
Yep - my first pass attempt at a solution here leaves an invalid term somewhere in the configuration so we're still generating something with incorrect semantics wrt. opaque pointers. I'll try again with your comment there for pointer / struct types and see if that gets us further.

**Comment by Baltoli** [comment]
Still broken for opaque pointer reasons; need to update the documentation for MacOS etc. to make sure users stay on version 15.
