### ISSUE TITLE
Support extra-verbose output from `llvm-krun`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#754]
Currently, `llvm-krun -v` only gives you a limited view of what's going on internally. If, for example, you're debugging an issue `kore-strip` or the other binary tools, the only way to get a hold of the commands being run is to patch `set -ex` into them.

**Comment by Robertorosmaninho** [comment]
The approach here is to use `set -x` on the beginning of the script (to see the whole execution), increase the use of `set -x` among binary tools calls of create levels of `--verbose` execution?

**Comment by Baltoli** [comment]
Two things are a bit conflated here:
* The actual logging of commands run by `llvm-krun`; that's related to `set -x` in response to a command line flag.
* The subcommands themselves producing verbose output; that means _propagating_ the verbose flags on to them if appropriate.
