### ISSUE TITLE
Implement exception handling for Python bindings

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/llvm-backend#758]
Right now, an error that occurs in bindings code kills the Python interpreter.

Example for one such error:

```
No tag found for symbol \left-assoc{}. Maybe attempted to evaluate a symbol with no rules?
```

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/llvm-backend/issues/623

**Comment by Baltoli** [comment]
Closing as duplicated
