### ISSUE TITLE
Pretty-print named non-terminals in `kprint`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#766]
Original context is here for Pyk: https://github.com/runtimeverification/pyk/issues/437. We would like to be able to print the names of non-terminals in a record production, as well as their values.

@dwightguth suggests the following solution (discussion on Slack [here](https://runtimeverification.slack.com/archives/C7E701MFG/p1684243898626889)):
* Emit the non-terminal names to syntaxDefinition.kore as attributes
* Look up that attribute when printing
* Care needs to be taken when there is an ellipsis present, or not all of the non-terminals have names

**Comment by dwightguth** [comment]
My main comment is simply that the goal of the unparser is to generate pretty printed code that, in most cases, can be parsed again into the same AST. Achieving this in all cases is difficult, but it is the goal when it can be achieved. Thus, if we pretty print the names of nonterminals, care must be taken to either modify the parser to support new syntax for parsing, or else only pretty print the names in such a manner that the parser can actually handle.

**Comment by Robertorosmaninho** [comment]
I'll have to modify the frontend in order to "Emit the non-terminal names to syntaxDefinition.kore as attributes", right?

**Comment by radumereuta** [comment]
Does `kprint` do anything other than interpret the `format` attribute from the `.kore` file?
If not, then the only thing we have to modify is the front end.
Probably this needs to be made smarter: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/unparser/Formatter.java#L131

**Comment by Robertorosmaninho** [comment]
@radumereuta, we probably want to open a new issue on the k frontend to address the space problems, as we'll have to refactor some tests to match this modification that aren't related to the non-terminals issue.

**Comment by Robertorosmaninho** [comment]
Fixed on https://github.com/runtimeverification/k/pull/3432
