### ISSUE TITLE
Issue with `%check-dir-diff` lit directive

### ISSUE THREAD

**Issue by mariaKt** [runtimeverification/llvm-backend#768]
There seems to be an issue with the `%check-dir-diff` check. Specifically, it seems to be able to report a failure in a test with multiple inputs only if the last input to run fails. I.e., if a KORE test has inputs in1, in2, in3, and failure occurs in in3, the test will be reported as a FAIL. If in2 fails, the run will continue and if in3 succeeds, the test will be reported as a PASS.

https://github.com/runtimeverification/llvm-backend/blob/046b5968778c4cb1fa8bc5b69918248e41504bb4/test/lit.cfg.py#L99

**Comment by Baltoli** [comment]
I confirmed that this is indeed the case; will investigate. Thanks @mariaKt!
