### ISSUE TITLE
Improve reporting of errors with `get_ui`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#771]
We should report hook errors more specifically by passing the name of the calling function through to `get_ui` when we use it; this will help people produce specific bug reports. I think the solution is to turn `get_ui` into a macro that expands `__pretty_function__` and calls a similar underlying `get_ui_named` implementation.

**Comment by Robertorosmaninho** [comment]
@Baltoli Could you provide more context about it? When did these errors happen? What would this `__pretty_function__` looks like?

**Comment by Robertorosmaninho** [comment]
Are you sure we want `__pretty_function__` instead of `__function__` ?
