### ISSUE TITLE
Expose more permissive API for config deserializer

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#781]
Motivated by the in-development format being used for the proof generation prototype, which embeds binary KORE objects as part of a larger file format.

We would like to expose a nicer API to the Python bindings, so that a _portion_ of a file-like object can be consumed to return a `_kllvm.KorePattern`, leaving the file at the end of the byte sequence representing that pattern.

I think this will require a bit of digging into the Python protocols for file-like objects to get a Pybind version working. Additionally, a clean implementation probably wants to bump the format version to include an extra bit of _size_ metadata in the files. We can keep version `1.1.0` backwards compatible when doing so.

Example Python code I might expect to see:
```python
with open('in.proof', 'b') as f:
    ... = f.read(...)
    term = pyk.kllvm.read_pattern(f)
    ... = f.read(...)
```

cc @gtrepta

**Comment by gtrepta** [comment]
@Baltoli If it's easier to have the deserializer just return the number of bytes read, then that's perfectly fine as well.
