### ISSUE TITLE
[GDB] `printValueOfType` is not compatible with opaque pointers

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#810]
This function performs an explicit comparison against the string value of pointer types; in LLVM 16 and onwards these values are all just `ptr` and so the check breaks.

The fix will be to use the `ValueType` available at the callsite, rather than the string values.

https://github.com/runtimeverification/llvm-backend/blob/b1f1e9c41322a7e3303eb8b973f379f82462d05c/runtime/util/ConfigurationPrinter.cpp#L343-L367C2

**Comment by radumereuta** [comment]
@Baltoli (if you have the time)
can you comment on this with more details about what needs to be done further here?
Is this related to GDB support?

**Comment by Baltoli** [comment]
Yes, this is indeed related to GDB support. The code in question is responsible for pretty-printing a runtime term from the backend; to do this, we need to know what type of term we're looking at (e.g. is the term a block pointer, a leaf value, an MPZ integer...). The representation used by the backend doesn't let you figure that out intrinsically, so we need to carry around some extrinsic information about what terms represent when we dispatch based on their type.

Typically in the backend we carry around a value of type [`ValueType`](https://github.com/runtimeverification/llvm-backend/blob/4c9d0101951dc7fa4f07b0b03f5afd84331a40f7/include/kllvm/ast/AST.h#L132-L142) for this purpose. The problematic code here does not do this, but rather dispatches on the textual representation of the LLVM IR type of the term pointer to be printed (is it a `%block *`, `%mpz_t *`...). In LLVM 16, a breaking change was made that collapses the type of pointer values into a single `%ptr` type, which means that the incorrect branch is selected because the textual values concerned have changed.

The fix for this issue is to amend the call site for this function to keep track of a `ValueType` and pass that information through, rather than checking textual representations of LLVM IR (the latter approach is likely to be fragile in the future for other reasons as well, and I'd consider it a minor code smell generally).

Let me know if any of this doesn't make sense; while I'm still off @Robertorosmaninho probably makes the most sense to fix this as the original author of the code IIRC.

**Comment by Robertorosmaninho** [comment]
Thanks for the clarification, Bruce! I'll try to investigate and fix this issue!

**Comment by Baltoli** [comment]
@Robertorosmaninho I presume that this would be usefully fixed in relation to your changes to enable batched testing of the debugger support?

**Comment by Robertorosmaninho** [comment]
Yes! That would be very helpful!
