### ISSUE TITLE
Expose definition parser to Python

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#815]
@tothtamas28 mentions that the Pyk KORE parser for definitions is being used in KEVM / Foundry, and represents a bit of a performance hotspot. We should add Python bindings for KORE definitions and the respective parser code to address this issue.

**Comment by Scott-Guest** [comment]
@tothtamas28 Could you point to where the definition parser is actually being used in KEVM / Foundry? 

Grepping for `KOREParser`, it looks like the only use is calling `pattern()` in `interpreter.py`, which could be handled by the existing parser bindings.

**Comment by tothtamas28** [comment]
> Could you point to where the definition parser is actually being used in KEVM / Foundry?

It is used through `pyk`: https://github.com/runtimeverification/pyk/blob/49f274d00d494741c07087248267d9169ce03f4a/src/pyk/kore/kompiled.py#L48
