### ISSUE TITLE
Memory leak in booster

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#816]
@jberthold and @goodlyrottenapple identify that there is a probable memory leak in the booster via the C bindings; this needs to be minimised down to an example that can be run directly via a C program (or indeed, via valgrind).

**Comment by geo2a** [comment]
I've collected a sample sequence of calls that seems to lead to slowly leaking memory. That is not really a minimal example unfortunately. The GHC evenlogs produced by tracing LLVM calls in the Booster grow very quickly, but I'm reluctant to try to minimize them to make sure the leak stays prominent.

Here's a gdrive link to [llvm_calls.c](https://drive.google.com/file/d/1du19d7gatwAW-dP7xC9zdkRzBMsZ5C8M/view?usp=sharing). Note that it's 60 MB, and it has been produced during only a fraction of one 'execute' RPC call. Additionally, I had to filter out calls that are longer than 2^16 bytes long (most likely bytecode token initialization) for GHC infrastructure reasons.

I hope this would be enough to start iterating.

**Comment by Baltoli** [comment]
This looks great, thanks @geo2a - should be enough for me to take a look at fixing the leaks.

**Comment by geo2a** [comment]
The approach of emitting `api.kore*` C calls from Booster proves to be cumbersome.

As an alternative, I've decided to try [heaptrack](https://github.com/KDE/heaptrack), which is a Linux heap profiling tool. This tool runs much faster than `valgring --leak-check=yes` and the leaks that it detects seem to agree with memory residency that I see in `htop`.

## What we're checking for leaks

First of all, we are running the `booster-dev` Haskell executable, which is a development version of `kore-rpc-booster` that **does not fall back to kore-rpc** (aka "the old Haskell backend"). This way we reduce the scope to the Haskell code in Booster and  the LLVM backend C library code it calls.

We're profiling a particular RPC `execute` request using KEVM-Foundry and a number of custom lemmas. The interaction is as follows:
* start the server `booster-dev definition.kore --llvm-backend-library ... --server-port ... --module ... `
* submit a request with `rpc-client send execute-request.json`, observer memory residency growing; repeat
* stop the server

## What we're seeing

Using the steps above, I've observed the memory residency grow by ~50 megabytes after each request. To get more specific data, we repeat the same steps, but now run the server under `heaptrack`, i.e. `heaptrack booster-dev ...`. I'm attaching two profiles, produced by running the request ones and ten times:
* [heaptrack.booster-dev-llvm-leak-execute-1.zst](https://drive.google.com/file/d/12gAbq-Cku5Zg-WAKKZuQTjo6TSZHU6no/view?usp=drive_link)
* [heaptrack.booster-dev-llvm-leak-execute-1.zst](https://drive.google.com/file/d/1sO20bUBXw4DhdFuE_9XP6dX9YVMjIBxK/view?usp=drive_link)

We need to install `heaptrack` to browse the data using `heaptrack_gui`:
```
heaptrack_gui heaptrack.booster-dev-llvm-leak-execute-10.zst
```
That's how the summary window looks for the profile that sends the same execute request 10 times:
![Screenshot_2023-08-01_11-55-00](https://github.com/runtimeverification/llvm-backend/assets/8296326/2512fa53-3e5a-463f-8760-69f78099b4c8)

Interestingly, `heaptrack` does not instrument the Haskell runtime, so we don't get any noise from it in these profiles!

@Baltoli could you have a look at these profiles and see if they make any sense? I'm happy to meet at any time to describe the workflow in more detail if needed.

**Comment by Baltoli** [comment]
This profile makes more sense to me - we've experienced similar issues in the Python bindings previously: https://github.com/runtimeverification/llvm-backend/issues/770

It's worth noting that the Haskell backend does a slightly more restricted set of operations than Python (i.e. constructing a function term + simplifying it, rather than executing a program via rewriting). What is the concurrency model used by the booster? The difficulty with the current GC is that while we could in theory add a feature to clear all the memory allocated by the GC arenas, that would trample on other threads' objects (see https://github.com/runtimeverification/llvm-backend/issues/705 where we identified the need for a global GC lock previously).

If the booster makes calls via the shared library in a thread / memory-safe way then we can _probably_ reduce the impact of this memory leak by adding a "free the world" function that gets called after each simplification is run (or at some other configurable threshold depending on performance). If not, given that this issue is cropping up for both Python and C bindings, we should perhaps try and find a way of redesigning / improving the LLVM backend's GC to avoid this pattern of leaking memory.

**Comment by goodlyrottenapple** [comment]
I seem to remember trying to run some GC function exported via the API, but that just caused seg-faults

**Comment by goodlyrottenapple** [comment]
Btw, the booster is currently single threaded-ish, in that we only ever run one request on the server (even tho it should be capable of handling multiple requests if there were multiple clients) and within that request, there are no concurrent calls to the LLVM shared library (I think).

**Comment by Baltoli** [comment]
Maybe that makes things easier then - will take a look at freeing the memory in a C example that doesn’t do rewriting, only function simplification and see where I get.

**Comment by geo2a** [comment]
Unfortunately, calling the existing primitives, `kllvm_init` and `kllvm_free_all_memory` does not seems to work, please see this [draft PR](https://github.com/runtimeverification/hs-backend-booster/pull/253) for details.

At his point, it is unclear what ways forward we have. Considering that we have other options to deal with mempry consumption in `kore-rpc-booster`, specifically killing the server and re-initializing it for long running proofs, I suggest we de-prioritize this issue for now.

**Comment by geo2a** [comment]
The issue has been resolved by https://github.com/runtimeverification/hs-backend-booster/pull/263, feel free to close! Thanks everyone!
