### ISSUE TITLE
[Debugger] `llvm-krun` doesn't support `lldb`

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/llvm-backend#852]
The default debugger for `llvm-krun` is assumed to be `gdb` instead of testing if it's in a Linux or Mac environment and then deciding which debugger to use.

**Comment by Baltoli** [comment]
I can see this is related to https://github.com/runtimeverification/llvm-backend/pull/851; is your intention that we have an autodetect mechanism as well as the `--debug-command` flag?
