### ISSUE TITLE
Switch away from mavenix

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/llvm-backend#929]
Since we have migrated away from mavenix in K, we should do the same here. We should do this by resurrecting #923, however, the reason this was reverted is that we rely on the `kore` package in `llvm-backend-matching`. This `kore` package is a snapshot generated each time we release K. This is a problem because when building in isolation in this repo, the dependency floats and the hash for deps changes with each release of K.

Ideally we should have the k release tag the kor epackage with a version number and then supply the version number when building `llvm-backend-matching`.

**Comment by Baltoli** [comment]
Not urgent; we can probably do some refactoring of the `kore` frontend package when we remove the Scala code later this year.

**Comment by Baltoli** [comment]
Fixed by https://github.com/runtimeverification/llvm-backend/pull/1012
