### ISSUE TITLE
Refactor side condition and rewrite events in proof traces

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#957]
Per @nishantjr on [Slack](https://runtimeverification.slack.com/archives/C05MF3KEWNM/p1705407588543239), there is an identified redundancy between the substitutions emitted into proof traces for rewrite and side condition events. Specifically, the substitution emitted for a side condition will _always_ be a subset of the substitution for the corresponding rule.

Nishant proposes the following changes to the proof trace format to eliminate the redundancy:
* Emit a side condition event for _every_ rule that matches (i.e. for rules without side conditions, a constant `true` result will be emitted).
* Do not emit the substitution and ordinal for side condition events.

The result of making this change will be that every rule event has a corresponding side condition event, and no substitutions are repeated redundantly.

The C++ parser for the trace format will need to be updated, along with a version bump to the format.

**Comment by nishantjr** [comment]
Thanks Bruce! Note that this will greatly simplify #727

**Comment by theo25** [comment]
@Baltoli @nishantjr It seems to me that the rule ordinal and the substitution are the only two pieces of information that we emit as part of a side condition hint. See here:
https://github.com/runtimeverification/llvm-backend/blob/2fdcb5953b4c40198a1ecaa8f91fae5b47d7100b/include/kllvm/binary/ProofTraceParser.h#L83-L95
https://github.com/runtimeverification/llvm-backend/blob/2fdcb5953b4c40198a1ecaa8f91fae5b47d7100b/include/kllvm/binary/ProofTraceParser.h#L42-L68

If that is the case indeed then isn't the task here equivalent to completely remove the generation of side condition hints and just assume by default that every rule event contains a corresponding side condition?

**Comment by nishantjr** [comment]
Indeed. The way I’m looking at it now, is that they are “try-rewrite”, and
“rewrite-succeeded” events.

In the previous version, since the side condition only included the partial
substitution in the side condition event, it would have forced us to apply
the substitution separately from the rewrite-event substitution when
proving rule application. This would have made the proof generation more
fragile and force us to have a separate optimization/clean up phase.
