### ISSUE TITLE
Incorrect hint location in trace

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/llvm-backend#989]
@IljaZakharov reports that when running the following definition:
`non-rec-function.k`:
```k
module NON-REC-FUNCTION-SYNTAX
  syntax Foo ::= "a"
               | bar(Foo)
               | baz(Foo)
               | id(Foo) [function, total]
endmodule

module NON-REC-FUNCTION
  imports NON-REC-FUNCTION-SYNTAX
  rule [id-rule]: id(X:Foo) => X
  rule [bar-rule]: bar(baz(X:Foo)) => id(id(bar(X)))
endmodule
```

With input `bar(baz(a))`, that:
> The location for the first simplification event is shorter than we expect it. It points to `id(id(bar(X)))` instead of its subterm `id(bar(X))`.

**Comment by Baltoli** [comment]
As far as I can tell, the location reported to me by the backend's parser is in fact correct and matches my understanding of the format.

The relevant section of the trace is:
```
...
rule: 98 3
  Var'Unds'DotVar0 = kore[61]
  Var'Unds'DotVar1 = kore[10]
  VarX = kore[48]
function: Lblid'LParUndsRParUnds'NON-REC-FUNCTION-SYNTAX'Unds'Foo'Unds'Foo{} (0:0:0)
  function: Lblid'LParUndsRParUnds'NON-REC-FUNCTION-SYNTAX'Unds'Foo'Unds'Foo{} (0:0:0:0)
    arg: kore[119]
  rule: 101 1
    VarX = kore[119]
  arg: kore[119]
rule: 101 1
  VarX = kore[119]
config: kore[288]
```

First, axiom 98 applies (`bar-rule`). The backend then enters the code generation step where it constructs the RHS term corresponding to `id(id(bar(X)))`, given some value for `X`. The logic for that - **heavily** simplified - looks something like this:
- Is the symbol at the top of the RHS a function symbol?
- It is (`id(_)`). Now:
  - Emit a function call _begin_ event into the trace (`0xDD` word, name, location info for this call - `0:0:0`)
  - Collect each argument so the actual call to `id` can be made.
  - The first argument is `id(bar(X))`. Is the symbol at the top a function symbol? _at this point we're in a recursive call stack_
    - Emit a function call _begin_ event into the trace (as above, location info is now `0:0:0:0`)
    - Collect each argument so the actual call to `id` can be made.
    - The first argument is `bar(X)`.
    - Call the evaluator for `id` with the value of `bar(X)`. _there's some logic to construct a `bar` term here; not important_
    - Emit a function call _end_ event (`0x11` word)
    - Emit a "rewrite applied" event for rule 101 (`id-rule`).
  - We now have the result of `id(bar(X))`, so we can call the evaluator for `id` with that value.
  - Emit a function call _end_ event.
  - Emit a "rewrite applied" event for rule 101.
- Top level rewrite end reached; emit a configuration.

**Comment by nishantjr** [comment]
@Baltoli This behaviour seems like it occurs for non-tail-recursive functions. We have a different behavior for tail-recursive functions, where the subsimplification happens after the sentinel. Can we keep the two behaviours the same, and even drop support for nested events?

**Comment by IljaZakharov** [comment]
This is the reverse-tree-int example, that we discussed before:

```
Init config: [kore]
Rule 130 [label: TREE-REVERSE-INT.rev-one-five] [loc: 22,27] [substs: 1]
  Var'Unds'DotVar0 = [kore]
Function: Lblreverse'LParUndsRParUnds'TREE-REVERSE-INT-SYNTAX'Unds'Tree'Unds'Tree{} @ 0:0:0
  Term: [kore]
Rule 216 [label: TREE-REVERSE-INT.rec-case] [loc: 19,24] [substs: 2]
  VarT1 = [kore]
  VarT2 = [kore]
Function: Lblreverse'LParUndsRParUnds'TREE-REVERSE-INT-SYNTAX'Unds'Tree'Unds'Tree{} @ 0:0
  Term: [kore]
Rule 215 [label: TREE-REVERSE-INT.base-case] [loc: 18,24] [substs: 2]
  VarX = [kore]
  Var'Unds'Gen0 = [kore]
Function: Lblreverse'LParUndsRParUnds'TREE-REVERSE-INT-SYNTAX'Unds'Tree'Unds'Tree{} @ 0:1
  Term: [kore]
Rule 215 [label: TREE-REVERSE-INT.base-case] [loc: 18,24] [substs: 2]
  VarX = [kore]
  Var'Unds'Gen0 = [kore]
Config: [kore]
```

**Comment by IljaZakharov** [comment]
The semantics for the example above:
```
module TREE-REVERSE-INT-SYNTAX

    imports INT-SYNTAX

    syntax Tree ::= node(Tree, Tree) | Int
    syntax Tree ::= reverse(Tree) [function, total]
    syntax KItem ::= "#reverse-one"
    syntax KItem ::= "#reverse-one-five"
    syntax KItem ::= "#next"

endmodule

module TREE-REVERSE-INT

    imports INT
    imports TREE-REVERSE-INT-SYNTAX

    rule [base-case] : reverse(X:Int) => X
    rule [rec-case] :  reverse(node(T1, T2)) => node(reverse(T2), reverse(T1))

    // Test simple injections in functions
    rule [rev-one-five] : <k> #reverse-one-five => reverse(node(1:Int, 5:Int)) </k>

    // Test reduction of nested injections
    rule [rev-one] : <k> #reverse-one => reverse(1) </k>

endmodule
```

**Comment by Baltoli** [comment]
The conclusion that we came to in today's meeting is that the proof trace preprocessing code will handle the current nested structure by understanding the order in which the backend emit function call begin events; there are no changes to the backend required at this time and so we can close this issue.
